spring.application.name=movie-booking-project-backend
spring.data.mongodb.database=MovieBookingProject
spring.data.mongodb.uri=mongodb+srv://jefferyfelshaw:SfoBkwSCz6CIGy8B@testcluster1.zkmsm4q.mongodb.net

 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=MovieBooking.notifications@gmail.com
spring.mail.password=asblctheafsoxhoq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true